version: '3.9'
services:
  # 
  nifi:
    image: apache/nifi
    container_name: nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=098765432100
    ports:
      - "8443:8443"
      - "5050:5050"
    volumes:
    - ./driver:/var
 
  #  
  mongo:
    container_name: mongo
    image: mongo
    command: --nojournal
    ports:
      - "27018:27017"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db-postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
volumes:
  mysql-db: ~