version: '3.9'
services:
  # 
  nifi:
    image: apache/nifi
    container_name: nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=098765432100
    ports:
      - "8443:8443"
 
  #  
  mongo:
    container_name: mongo
    image: mongo
    command: --nojournal
    ports:
      - "27018:27017"

  db-mysql:
    image: mysql:5.7.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./driver:/opt
volumes:
  mysql-db: ~